### ISSUE TITLE
Slave with higher charges may not communicate

### ISSUE THREAD

**Issue by hallard** [dev-lab/esp-iot-mbus#1]
Not really an issue but wanted to add it as a reminder and inform you and other.

I'm using your schematics (with 34V done from 3.6V by an AP3015) all is working fine, just wanted to let you know that on some mbus device that are referenced such as "4 x mbus slave charge" (so approx 7.5mA consumption) I had some issues to communicate.

I solved this point decreasing R14 from 82ohm to 47ohm (not sure of the incidence on others).
I'm using BC807 transistor instead of KT814 (BD136), I may need to find another one with lower VCE sat, BC807 is 0.7V max and BD136 is 0.5V.

Any hints on this, should it be correct?

**Comment by dev-lab** [comment]
In my circuit I am making 36V from 5V using the Y4169 module, although I have indicated that other modules capable of providing 36V DC can be used (such as the XL6019 or XL6009).
You are obviously using a different circuit (AP3015 based) which I believe may be the cause of the problem. For example, it may not be able to provide a reliable constant voltage that is independent of the amount of current your m-bus draws depending on read/write mode.
To solve the problem, I would recommend using a bench power supply for +36V first, and only change the circuit if it won't work properly with your m-bus device.

**Comment by hallard** [comment]
@dev-lan thanks,
Interesting but AP3015 is able to provide 300mA at 34V with only 200mV drop, so MBus device 7.5mA charge should be far enough not? 
https://www.diodes.com/assets/Datasheets/AP3015_A.pdf
Anyway I can try another one as you suggest, but I suspect my dual serial Energizer Lithium 1.8V (to power at 3.6V) drops too much (approx 150mA) wen DC/DC activated to provide 34V and even more when MBus communicate.

Anyway looked at your module, they are breakout board like, I can't put them on our board, because I also need enable pin to shut down DC/DC during sleep mode and I'm space contrainst.

**Comment by hallard** [comment]
Just to let you know that I was also able also to use schematics with only 24V power, as soon as only one device is connected and wire are not too long (generally the case), moving R14 in between 47 and 82 Ohm can help.
Thanks for your great job.

**Comment by dev-lab** [comment]
@hallard Thanks for your feedback!
I’ll probably update the project description later to include your suggestion about tuning R14 — in case someone else decides to experiment with the lowest voltages from the M-Bus spec and those "4 x mbus slave charge" meters.

**Comment by hallard** [comment]
You're welcome,
using 24V is no problem with 82 Ohm.
Just needed to reduce R14 to 47 Ohm with device consuming "4 x mbus slave charge" or more,  whatever voltage I'm using (24V to 34V)
